# -*- coding: utf-8 -*-
"""esercizi_python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yYAB8aEtNdzoEvt5mxn4mblN4L6EEO5Z

Esercizio 1
Dichiarare una variabile "nome" e assegnargli il tuo nome. Mandare a schermo.
"""

nome="Antonio"
print(nome)

"""Esercizio 2
Dichiarare una variabile "eta" e assegnargli la tua età. Mandare a schermo.
"""

eta = 22
print(eta)

"""Esercizio 3
Dichiarare una variabile "pi" e assegnargli il valore di pi greco (3,14159). Mandare a schermo.


"""

import math
print(math.pi)

"""Esercizio 4
Creare una variabile "lunghezza" e assegnargli un valore, quindi riassegnare la variabile a 15. Mandare a schermo.
"""

lunghezza = 10
print(lunghezza)
lunghezza = 15
print(lunghezza)

"""Esercizio 5
Creare una variabile "nome_completo" e assegnargli una stringa contenente il tuo nome e cognome. Mandare a schermo
"""

nome_completo = "Antonio Cifarelli"
print(nome_completo)

nome="Antonio"
cognome="Cifarelli"
nome_completo=nome+" "+cognome
print(nome_completo)

"""Esercizio 6
Creare una variabile "eta_futura" e assegnargli il valore dell'età che avrai tra 10 anni (utilizzando la variabile età già esistente). Mandare a schermo.


"""

eta_futura = eta + 10
print(eta_futura)

"""Esercizio 7
Creare delle variabili "nome", "cognome" ed "anno_di_nascita" ed assegnargli i valori. Mandare a schermo in un unico print. Sovrascrivere tutte le variabili e rimandare a schermo una seconda volta.


"""

nome = "Antonio"
cognome = "Cifarelli"
anno_di_nascita = 2003
print(nome, cognome, anno_di_nascita)
print(nome + " " + cognome + " " + str(anno_di_nascita))

"""Esercizio 8
Creare una variabile eta_attuale e assegnargli il valore dell'età che hai attualmente, calcolandola in base all'anno corrente. Mandare a schermo eta_attuale
"""

eta_attuale = 2025 - anno_di_nascita
print(eta_attuale)